"""
Keyword Extractor — Deterministic ATS keyword scoring engine.

This module handles Layer 1 of the hybrid ATS scoring system:
1. Extracts technical keywords from job descriptions (not soft skills)
2. Converts LaTeX resumes to searchable plain text
3. Matches JD keywords against resume text with synonym normalization
4. Calculates a deterministic score using a fixed formula

The score is NEVER generated by an LLM — it's pure Python math.

Scoring Formula:
    keyword_score     = (matched_required / total_required) * 60     [0-60]
    preferred_score   = (matched_preferred / total_preferred) * 20   [0-20]
    ai_quality_score  = LLM provides this (experience alignment)     [0-20]
    ---------------------------------------------------------------
    final_score       = keyword_score + preferred_score + ai_quality_score

Hard Penalties (applied after sum):
    - Domain mismatch (resume is in a completely unrelated field):  -20
    - Experience gap (each year short of JD requirement):          -10 per year
    - Final score clamped to [0, 100]
"""

import re
from typing import Optional


# ======================================================================
# SYNONYM MAP — normalizes common tech keyword variations
# Keys are canonical forms; values are alternate spellings the JD
# or resume might use. Both directions are checked during matching.
# ======================================================================
SYNONYM_MAP: dict[str, list[str]] = {
    "javascript":       ["js", "es6", "es2015", "ecmascript"],
    "typescript":       ["ts"],
    "python":           ["py", "python3"],
    "react":            ["react.js", "reactjs", "react js"],
    "angular":          ["angular.js", "angularjs", "angular js"],
    "vue":              ["vue.js", "vuejs", "vue js"],
    "next.js":          ["nextjs", "next js", "next"],
    "node.js":          ["nodejs", "node js", "node"],
    "express":          ["express.js", "expressjs"],
    "postgresql":       ["postgres", "psql", "pgsql"],
    "mongodb":          ["mongo"],
    "mysql":            ["my sql"],
    "redis":            ["redis cache"],
    "docker":           ["containerization", "containers"],
    "kubernetes":       ["k8s", "kube"],
    "amazon web services": ["aws"],
    "google cloud platform": ["gcp", "google cloud"],
    "microsoft azure":  ["azure"],
    "machine learning": ["ml"],
    "deep learning":    ["dl"],
    "natural language processing": ["nlp"],
    "computer vision":  ["cv"],
    "artificial intelligence": ["ai"],
    "continuous integration": ["ci"],
    "continuous deployment":  ["cd"],
    "ci/cd":            ["ci cd", "cicd"],
    "graphql":          ["graph ql"],
    "rest api":         ["restful api", "restful", "rest"],
    "terraform":        ["tf", "iac"],
    "tailwind css":     ["tailwindcss", "tailwind"],
    "sass":             ["scss"],
    "html":             ["html5"],
    "css":              ["css3"],
    "c++":              ["cpp", "c plus plus"],
    "c#":               ["csharp", "c sharp"],
    ".net":             ["dotnet", "dot net"],
    "spring boot":      ["springboot", "spring"],
    "ruby on rails":    ["rails", "ror"],
    "flask":            ["flask framework"],
    "django":           ["django framework"],
    "fastapi":          ["fast api"],
    "pandas":           ["pd"],
    "numpy":            ["np"],
    "scikit-learn":     ["sklearn", "scikit learn"],
    "tensorflow":       ["tf framework"],
    "pytorch":          ["torch"],
    "jenkins":          ["jenkins ci"],
    "github actions":   ["gh actions"],
    "elasticsearch":    ["elastic search", "elastic"],
    "apache kafka":     ["kafka"],
    "apache spark":     ["spark", "pyspark"],
    "power bi":         ["powerbi"],
    "tableau":          ["tableau desktop"],
    "figma":            ["figma design"],
    "jira":             ["jira software"],
    "agile":            ["agile methodology", "scrum", "kanban"],
    "devops":           ["dev ops"],
    "microservices":    ["micro services"],
    "api":              ["apis", "web api"],
    "sql":              ["structured query language"],
    "nosql":            ["no sql", "non-relational"],
    "git":              ["version control", "github", "gitlab", "bitbucket"],
    "linux":            ["unix", "ubuntu", "centos", "debian"],
    "java":             ["jdk", "jre", "jvm"],
    "go":               ["golang"],
    "rust":             ["rust lang"],
    "swift":            ["swift lang"],
    "kotlin":           ["kt"],
    "r":                ["r lang", "r programming"],
    "matlab":           ["mat lab"],
    "supabase":         ["supabase db"],
    "firebase":         ["firebase sdk"],
}

# ======================================================================
# SOFT SKILLS — excluded from keyword extraction because real ATS
# systems don't score on subjective traits.
# ======================================================================
SOFT_SKILLS: set[str] = {
    "communication", "teamwork", "leadership", "problem solving",
    "problem-solving", "adaptability", "creativity", "critical thinking",
    "time management", "collaboration", "attention to detail",
    "self-motivated", "motivated", "interpersonal", "work ethic",
    "organizational", "multitasking", "flexibility", "initiative",
    "analytical", "verbal", "written", "presentation", "negotiation",
    "conflict resolution", "decision making", "mentoring", "coaching",
    "empathy", "patience", "reliability", "accountability",
    "professionalism", "self-starter", "proactive", "detail-oriented",
    "results-driven", "fast learner", "quick learner", "team player",
    "strong communicator", "excellent communication",
    "passionate", "enthusiastic", "dedicated", "hardworking",
}

# ======================================================================
# SIGNAL PHRASES — used to classify keywords as required vs preferred
# ======================================================================
REQUIRED_SIGNALS: list[str] = [
    "required", "must have", "must-have", "essential",
    "mandatory", "minimum", "core", "fundamental",
    "proficiency in", "proficient in", "strong experience",
    "deep understanding", "solid understanding",
    "experience with", "expertise in", "knowledge of",
    "responsibilities", "qualifications",
]

PREFERRED_SIGNALS: list[str] = [
    "preferred", "nice to have", "nice-to-have", "bonus",
    "plus", "a plus", "advantageous", "desirable",
    "familiarity with", "exposure to", "ideally",
    "good to have", "optional",
]


# ======================================================================
# TECH KEYWORDS DICTIONARY — broad set of known tech terms
# ======================================================================
TECH_KEYWORDS: set[str] = set()

# Populate from synonym map keys + their synonyms
for _canonical, _syns in SYNONYM_MAP.items():
    TECH_KEYWORDS.add(_canonical.lower())
    for _s in _syns:
        TECH_KEYWORDS.add(_s.lower())

# Additional common tech terms not covered by the synonym map
TECH_KEYWORDS.update({
    "webpack", "vite", "babel", "parcel", "rollup",
    "graphql", "grpc", "websocket", "websockets",
    "oauth", "jwt", "saml", "sso",
    "rabbitmq", "celery", "airflow",
    "nginx", "apache", "caddy",
    "prometheus", "grafana", "datadog", "new relic",
    "sentry", "splunk", "kibana",
    "arm", "fpga", "embedded",
    "opencv", "yolo", "transformers", "bert", "gpt",
    "llm", "rag", "langchain", "vector database",
    "pinecone", "weaviate", "qdrant", "chromadb",
    "snowflake", "databricks", "dbt",
    "looker", "metabase", "superset",
    "cypress", "jest", "pytest", "mocha", "selenium",
    "playwright", "vitest", "unittest",
    "svelte", "remix", "nuxt", "gatsby",
    "three.js", "d3.js", "chart.js",
    "flutter", "react native", "ionic", "xamarin",
    "swiftui", "jetpack compose",
    "solidity", "web3", "blockchain", "ethereum",
    "unity", "unreal engine",
    "openai", "groq", "huggingface", "anthropic",
    "latex", "tectonic",
    "data structures", "algorithms", "system design",
    "design patterns", "object oriented", "oop",
    "functional programming",
    "data engineering", "data science", "data analysis",
    "etl", "data pipeline", "data warehouse",
    "aws lambda", "s3", "ec2", "ecs", "eks", "rds",
    "dynamodb", "sqs", "sns", "cloudformation", "cdk",
    "gke", "cloud run", "bigquery", "cloud functions",
    "aks", "cosmos db", "blob storage",
})


# ======================================================================
# PUBLIC API
# ======================================================================

def latex_to_plain_text(latex_code: str) -> str:
    """
    Convert LaTeX source code to searchable plain text.

    Strips LaTeX commands, preamble, environments, and formatting
    while preserving the actual text content that an ATS would see.
    """
    text = latex_code

    # Remove comments (lines starting with %)
    text = re.sub(r'%.*$', '', text, flags=re.MULTILINE)

    # Remove documentclass and usepackage declarations
    text = re.sub(r'\\documentclass\b[^{]*\{[^}]*\}', '', text)
    text = re.sub(r'\\usepackage\b[^{]*\{[^}]*\}', '', text)

    # Remove preamble-only commands (consume the rest of their line)
    text = re.sub(
        r'\\(?:pagestyle|thispagestyle|setlength|setcounter|newcommand|'
        r'renewcommand|def|geometry|hypersetup|titleformat|titlespacing|'
        r'pagenumbering|addtolength|input|include)\b[^\n]*',
        '', text
    )

    # Remove \begin{...} and \end{...} environment markers
    text = re.sub(r'\\(?:begin|end)\{[^}]*\}', '', text)

    # Convert text-formatting commands to their content:
    # \textbf{content} -> content, \emph{content} -> content, etc.
    text = re.sub(
        r'\\(?:textbf|textit|textsc|emph|underline|textnormal|mbox)\{([^}]*)\}',
        r'\1', text
    )

    # \href{url}{display text} -> display text
    text = re.sub(r'\\href\{[^}]*\}\{([^}]*)\}', r'\1', text)

    # \section{Title} -> Title  (preserve heading text)
    text = re.sub(
        r'\\(?:section|subsection|subsubsection)\*?\{([^}]*)\}',
        r'\1', text
    )

    # Remove \item markers, keep the bullet text that follows
    text = re.sub(r'\\item\b\s*', ' ', text)

    # Remove all remaining LaTeX commands (\commandname or \commandname*)
    text = re.sub(r'\\[a-zA-Z]+\*?', ' ', text)

    # Remove braces and brackets
    text = re.sub(r'[{}\[\]]', ' ', text)

    # Remove special LaTeX characters
    text = re.sub(r'[~$&#^_]', ' ', text)

    # Remove stray backslashes
    text = re.sub(r'\\', ' ', text)

    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    return text


def extract_keywords_from_jd(
    job_description: str,
) -> tuple[list[str], list[str]]:
    """
    Extract technical keywords from a job description and classify
    them as 'required' or 'preferred'.

    Strategy:
    1. Scan the JD text for known tech terms (from TECH_KEYWORDS set)
    2. Use regex to catch multi-word patterns (e.g. "React Native")
    3. Classify based on proximity to required/preferred signal phrases
    4. Filter out soft skills
    5. Deduplicate using canonical synonym forms

    Returns:
        (required_keywords, preferred_keywords) — both lists of
        canonical, lowercased keyword strings.
    """
    jd_lower = job_description.lower()

    # -- Step 1: Find all tech keywords present in the JD --
    found_keywords: set[str] = set()

    # Check multi-word terms first (longest match priority)
    sorted_tech = sorted(TECH_KEYWORDS, key=len, reverse=True)

    for term in sorted_tech:
        if len(term.split()) > 1:
            # Multi-word: substring match
            if term in jd_lower:
                found_keywords.add(_get_canonical(term))
        else:
            # Single word: word boundary to avoid "Java" matching "JavaScript"
            if re.search(r'\b' + re.escape(term) + r'\b', jd_lower):
                found_keywords.add(_get_canonical(term))

    # Also check canonical synonym map keys + their synonyms
    for canonical, synonyms in SYNONYM_MAP.items():
        canon_lower = canonical.lower()
        if _term_in_text(canon_lower, jd_lower):
            found_keywords.add(canon_lower)
        for syn in synonyms:
            if _term_in_text(syn.lower(), jd_lower):
                found_keywords.add(canon_lower)

    # -- Step 2: Remove soft skills --
    found_keywords = {kw for kw in found_keywords if kw not in SOFT_SKILLS}

    # -- Step 3: Classify into required vs preferred --
    required: list[str] = []
    preferred: list[str] = []

    for kw in found_keywords:
        if _classify_keyword(kw, jd_lower) == "preferred":
            preferred.append(kw)
        else:
            required.append(kw)

    # Sort for deterministic output
    required.sort()
    preferred.sort()

    return required, preferred


def match_keywords_against_resume(
    keywords: list[str],
    resume_plain_text: str,
) -> tuple[list[str], list[str]]:
    """
    Check which JD keywords are present in the resume plain text.
    Uses synonym normalization so "React.js" matches "React", etc.

    Returns:
        (matched, missing) — two lists of keyword strings.
    """
    resume_lower = resume_plain_text.lower()
    matched: list[str] = []
    missing: list[str] = []

    for kw in keywords:
        if _keyword_found_in_text(kw, resume_lower):
            matched.append(kw)
        else:
            missing.append(kw)

    return matched, missing


def calculate_deterministic_score(
    matched_required: int,
    total_required: int,
    matched_preferred: int,
    total_preferred: int,
    ai_quality_score: int,
    domain_mismatch: bool,
    experience_gap_years: int,
) -> tuple[int, dict]:
    """
    Calculate the final ATS score using a fixed, deterministic formula.

    This function is the ONLY place the final score is computed.
    The LLM never sets the score — only provides the quality_score input.

    Formula:
        keyword_score   = (matched_required / total_required) * 60
        preferred_score = (matched_preferred / total_preferred) * 20
        quality_score   = ai_quality_score (clamped to 0-20)
        raw_score       = keyword_score + preferred_score + quality_score

    Penalties:
        - domain_mismatch:  -20
        - experience_gap:   -10 per year short

    Returns:
        (final_score, breakdown_dict)
    """
    # -- Component scores --
    if total_required > 0:
        keyword_score = round((matched_required / total_required) * 60)
    else:
        keyword_score = 60  # No required keywords extracted -> full credit

    if total_preferred > 0:
        preferred_score = round((matched_preferred / total_preferred) * 20)
    else:
        preferred_score = 20  # No preferred keywords -> full credit

    quality_score = max(0, min(20, ai_quality_score))

    # -- Raw total --
    raw_score = keyword_score + preferred_score + quality_score

    # -- Hard penalties --
    penalty = 0
    if domain_mismatch:
        penalty += 20
    if experience_gap_years > 0:
        penalty += experience_gap_years * 10

    final_score = max(0, min(100, raw_score - penalty))

    # -- Breakdown for the frontend --
    breakdown = {
        "keyword_score": keyword_score,
        "keyword_max": 60,
        "preferred_score": preferred_score,
        "preferred_max": 20,
        "quality_score": quality_score,
        "quality_max": 20,
        "raw_score": raw_score,
        "domain_penalty": -20 if domain_mismatch else 0,
        "experience_penalty": -(experience_gap_years * 10) if experience_gap_years > 0 else 0,
        "total_penalty": -penalty,
        "final_score": final_score,
    }

    return final_score, breakdown


def parse_experience_gap(experience_gap_str: str) -> int:
    """
    Parse the LLM's experience_gap string to extract how many years
    the candidate is short.

    Examples:
        "JD requires 5 years, resume shows 2 — 3 years short" -> 3
        "none" -> 0
        "No experience gap detected" -> 0
    """
    if not experience_gap_str:
        return 0

    gap_lower = experience_gap_str.lower().strip()

    # Explicit "none" / "no gap"
    if gap_lower in ("none", "n/a", "no gap", "0"):
        return 0
    if "no experience gap" in gap_lower or "no gap" in gap_lower:
        return 0
    if "meets" in gap_lower or "exceeds" in gap_lower:
        return 0

    # Pattern: "X year(s) short"
    match = re.search(r'(\d+)\s*year[s]?\s*short', gap_lower)
    if match:
        return int(match.group(1))

    # Pattern: two year numbers -> compute difference
    # e.g., "requires 5 years, resume shows 2"
    numbers = re.findall(r'(\d+)\s*(?:\+\s*)?year', gap_lower)
    if len(numbers) >= 2:
        required_years = int(numbers[0])
        actual_years = int(numbers[1])
        return max(0, required_years - actual_years)

    # Single number with gap language
    if "short" in gap_lower or "less" in gap_lower or "gap" in gap_lower:
        numbers = re.findall(r'(\d+)', gap_lower)
        if numbers:
            return int(numbers[0])

    return 0


# ======================================================================
# INTERNAL HELPERS
# ======================================================================

def _term_in_text(term: str, text: str) -> bool:
    """Check if a term appears in text, using word boundaries for single words."""
    if len(term.split()) > 1:
        return term in text
    return bool(re.search(r'\b' + re.escape(term) + r'\b', text))


def _get_canonical(term: str) -> str:
    """
    Given a keyword (possibly a synonym), return the canonical form.
    If not in the synonym map, returns the term itself lowercased.
    """
    term_lower = term.lower().strip()

    if term_lower in SYNONYM_MAP:
        return term_lower

    for canonical, synonyms in SYNONYM_MAP.items():
        if term_lower in [s.lower() for s in synonyms]:
            return canonical.lower()

    return term_lower


def _keyword_found_in_text(keyword: str, text_lower: str) -> bool:
    """
    Check if a keyword (or any of its synonyms) appears in the text.
    """
    # Collect all forms: canonical + synonyms
    forms_to_check = {keyword.lower()}

    kw_lower = keyword.lower()
    if kw_lower in SYNONYM_MAP:
        forms_to_check.update(s.lower() for s in SYNONYM_MAP[kw_lower])

    for canonical, synonyms in SYNONYM_MAP.items():
        if kw_lower in [s.lower() for s in synonyms]:
            forms_to_check.add(canonical.lower())
            forms_to_check.update(s.lower() for s in synonyms)

    # Check each form
    for form in forms_to_check:
        if len(form.split()) > 1:
            if form in text_lower:
                return True
        else:
            escaped = re.escape(form)
            if re.search(r'\b' + escaped + r'\b', text_lower):
                return True
            # Fallback for special chars (c++, c#, .net)
            if form in text_lower:
                return True

    return False


def _classify_keyword(keyword: str, jd_lower: str) -> str:
    """
    Classify a keyword as 'required' or 'preferred' based on
    proximity to signal phrases in the JD text.

    Default is 'required' — only reclassified if found near
    a preferred-signal AND not also near a required-signal.
    """
    kw_lower = keyword.lower()

    # Find all positions of this keyword (including synonym forms)
    kw_positions = []
    forms = {kw_lower}
    if kw_lower in SYNONYM_MAP:
        forms.update(s.lower() for s in SYNONYM_MAP[kw_lower])
    for canonical, synonyms in SYNONYM_MAP.items():
        if kw_lower in [s.lower() for s in synonyms]:
            forms.add(canonical.lower())
            forms.update(s.lower() for s in synonyms)

    for form in forms:
        kw_positions.extend(m.start() for m in re.finditer(re.escape(form), jd_lower))

    if not kw_positions:
        return "required"

    # Check if ANY occurrence is near a preferred signal
    near_preferred = False
    near_required = False

    for signal in PREFERRED_SIGNALS:
        for sig_pos in (m.start() for m in re.finditer(re.escape(signal), jd_lower)):
            for kw_pos in kw_positions:
                if abs(kw_pos - sig_pos) < 200:
                    near_preferred = True

    for signal in REQUIRED_SIGNALS:
        for sig_pos in (m.start() for m in re.finditer(re.escape(signal), jd_lower)):
            for kw_pos in kw_positions:
                if abs(kw_pos - sig_pos) < 200:
                    near_required = True

    # Only classify as preferred if near a preferred signal
    # AND NOT also near a required signal
    if near_preferred and not near_required:
        return "preferred"

    return "required"
